import Head from "next/head";
import os from "os";
import { useEffect, useState } from "react";
import DeviceDetect from "../components/maxTouchDetect";

export default function Home() {
  // let cpu = os.cpus();
  console.log(os.userInfo);
  const [info, setinfo] = useState("");
  useEffect(() => {}, [info]);
  const getInfo = (data) => {
    setinfo(data);
  };

  return (
    <div className="bg-gray-200 min-h-screen min-w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-700 text-black text-3xl font-bold underline">
        what
      </div>
      <button onClick={() => getInfo(os.userInfo)}>click</button>
      <div>THis is data {JSON.stringify(info)}</div>
      <div>
        <DeviceDetect />
      </div>
    </div>
  );
}
